#!/usr/bin/env python3
"""
Main file
"""
from auth import Auth

email = 'bob@bob.com'
password = 'MyPwdOfBob'
auth = Auth()
auth.register_user(email, password)
auth.get_reset_password_token(email)

session = auth.create_session(email)
print(session)
print(dict(auth.get_user_from_session_id(session)))
print(auth.create_session("unknown@email.com"))
